Updated to latest Pega configs and udpated eslint
pegasystems/web-components-sdk pull request #141
Opened 2024-02-21 18:25 UTC by niallriddell

2024-02-23 19:23 UTC, tumms2021389 approved these changes
Looks good to me

just added a small comment

2024-02-24 18:28 UTC, tumms2021389 requested changes

2024-02-24 18:28 UTC, tumms2021389 commented on sdk-config.json
> +    "infinityRestServerUrl": "https://lab0427.lab.pega.com/prweb",
change this to localhost url

2024-02-24 18:28 UTC, tumms2021389 commented on package.json
> +    "@pega/constellationjs": "~23.1.1",
please uninstall constellationjs package from dependencies

2024-02-26 12:10 UTC, niallriddell commented on package.json
> +    "@pega/constellationjs": "~23.1.1",
All done.

2024-02-26 12:11 UTC, niallriddell commented on sdk-config.json
> +    "infinityRestServerUrl": "https://lab0427.lab.pega.com/prweb",
Done

2024-02-27 18:14 UTC, tumms2021389 approved these changes

2024-02-29 09:44 UTC, closed without merging