Fixed the issues identified while internal adoption testing
pegasystems/web-components-sdk pull request #184
Opened 2024-09-16 14:07 UTC by 4manasa

2024-09-18 10:29 UTC, niallriddell requested changes
Please use narrower types

2024-09-18 10:29 UTC, niallriddell commented on src/components/templates/CaseView/index.ts
> +  editAction: any;
Use of any.

2024-09-19 10:55 UTC, 4manasa commented on src/components/templates/CaseView/index.ts
> +  editAction: any;
Updated

2024-09-19 15:34 UTC, niallriddell commented on src/components/templates/CaseView/index.ts
> +  links: any;
Use of any?  Can we find a narrower type?

2024-09-19 15:36 UTC, niallriddell requested changes
See if you can find a better type for links.

2024-09-20 15:26 UTC, niallriddell approved these changes
Happy to approve, but Object is only slightly narrower than any.  Not so bothered as links does not appear to be directly referenced.

2024-09-23 05:19 UTC, merged

2024-09-23 08:25 UTC, niallriddell reviewed
lgtm